# Site settings
title: Jing Yi Li
email: lijing3931@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Portfolio website of Jing Yi Li, recent computer science UCSD graduate."
keywords: "your keywords, separated by commas"
skills: "Data Analytics - Software Development"
meta_author: Li Jing Yi

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jing Yi Li
  social: Socials

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jing3li/
  - title: github
    url: https://github.com/j3li
  - title: google
    url: mailto:lijing3931@gmail.com

# Postal address (add as many lines as necessary)
# address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  visualizations:
    output: true
  projects:
    output: true

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
